@url = https://glorious-space-xylophone-wxxx5xw45r9hvg5-8080.app.github.dev/generos

GET {{url}}

###
POST {{url}}
Content-Type: application/json

{
    "nome": "Ação"
}

###
GET {{url}}/1

###
PUT {{url}}/1
Content-Type: application/json
{
    "nome":"Aventura"
}

###
DELETE {{url}}/1